In [1]:
# Dependency
import pandas as pd

In [2]:
# read in CSV
mv_df = pd.read_csv('Resources/the-movies-dataset/movies_metadata.csv')

/Users/brian.abbe/anaconda3/envs/Pythondata/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
# remove unnecessary columns and rows with null data
mv_dropped = mv_df.drop(columns={'belongs_to_collection', 'genres', 'spoken_languages', 'imdb_id',\
                                 'id', 'homepage', 'production_companies', 'production_countries'\
                                , 'poster_path', 'status', 'original_title', 'video', 'overview'\
                                ,'tagline', 'adult'})
mv_dropped = mv_dropped.dropna()

In [4]:
# Convert columns to integers for filtering
mv_dropped['runtime'] = mv_dropped['runtime'].astype(int)
mv_dropped['revenue'] = mv_dropped['revenue'].astype(int)
mv_dropped['vote_count'] = mv_dropped['vote_count'].astype(int)
mv_dropped['budget'] = mv_dropped['budget'].astype(int)

In [5]:
# filter via loc
mv_filtered = mv_dropped.loc[(mv_dropped['revenue'] > 0)]
mv_filtered = mv_filtered.loc[(mv_filtered['vote_count'] > 1000)]
mv_filtered = mv_filtered.loc[(mv_filtered['budget'] > 0)]
mv_filtered = mv_filtered.loc[(mv_filtered['original_language'] == 'en')]

In [6]:
# extract the year only from the release date
mv_filtered['release_date'] = pd.to_datetime(mv_filtered['release_date'])
mv_filtered['release_date'] = mv_filtered['release_date'].map(lambda x: x.year)

In [7]:
# set title as the index, sort by vote scores and remove the language column now that we have filtered by language
df_final = mv_filtered.sort_values(by=['vote_average'], ascending=False)
df_final = df_final.drop(columns={'original_language'})
df_final = df_final.set_index('title')
df_final

,budget,popularity,release_date,revenue,runtime,vote_average,vote_count
title,,,,,,,
The Godfather,6000000,41.1093,1972,245066411,175,8.5,6024
The Shawshank Redemption,25000000,51.6454,1994,28341469,142,8.5,8358
Fight Club,63000000,63.8696,1999,100853753,139,8.3,9678
Schindler's List,22000000,41.7251,1993,321365567,195,8.3,4436
One Flew Over the Cuckoo's Nest,3000000,35.5296,1975,108981275,133,8.3,3001
...,...,...,...,...,...,...,...
The Last Airbender,150000000,9.54466,2010,318502923,103,4.7,1180
Ghost Rider: Spirit of Vengeance,57000000,9.4213,2011,149217355,95,4.7,1163
Fantastic Four,120000000,17.2465,2015,167977596,100,4.4,2322
Batman & Robin,125000000,17.0388,1997,238207122,125,4.2,1447
The Boy Next Door,4000000,10.2004,2015,52425855,91,4.1,1034

In [9]:
# Export to CSV
df_export = df_final.to_csv(r'Resources/final_movie_metadata.csv', index = True, header=True)