In [2]:
import pandas as pd

df = pd.read_csv('../Resources/rotten_tomatoes_reviews.csv')
df

,rotten_tomatoes_link,review_date,critic_publication,critic_icon,critic_top,critic_score,review_content
0,/m/0814255,2015-01-09,Cinemaphile.org,Rotten,NaN,NaN,The plot uses the presence of the Greek gods a...
1,/m/0814255,2012-07-31,7M Pictures,Fresh,NaN,NaN,It provides a great adventure movie for the fa...
2,/m/0814255,2011-11-05,"Star-Democrat (Easton, MD)",Rotten,NaN,NaN,The premise of Percy Jackson & the Olympians: ...
3,/m/0814255,2011-04-25,ComingSoon.net,Rotten,NaN,NaN,Percy Jackson is simply uninspired in every si...
4,/m/0814255,2011-04-04,Movies.com,Rotten,NaN,NaN,It kind of just builds up to a lot of Not Much.
5,/m/0814255,2010-08-04,Window to the Movies,Fresh,NaN,NaN,Manages to pay its respects to the Greek myths...
6,/m/0814255,2010-07-17,Matt's Movie Reviews,Fresh,NaN,NaN,Percy Jackson & the Olympians: The Lightning T...
7,/m/0814255,2010-07-06,Boston Phoenix,Rotten,NaN,NaN,Mildly diverting.
8,/m/0814255,2010-07-06,Groucho Reviews,Fresh,NaN,NaN,An enjoyable PG-rated family adventure in its ...
9,/m/0814255,2010-07-06,JoBlo's Movie Emporium,Rotten,NaN,NaN,"Just another mediocre fantasy flick, but if yo..."
10,/m/0814255,2010-07-04,Cinema Sight,Fresh,NaN,NaN,"Not a perfect film, but the movie does have a ..."
11,/m/0814255,2010-06-30,Movie Metropolis,Fresh,NaN,NaN,"A great family film, with just the right measu..."
12,/m/0814255,2010-05-16,TheMovieReport.com,Rotten,NaN,NaN,Of all the would-be Potter projects that have ...
13,/m/0814255,2010-03-26,Movies for the Masses,Rotten,NaN,NaN,click to read full review
14,/m/0814255,2010-03-14,Sacramento News & Review,Fresh,NaN,NaN,... a sprightly Harry Potter clone and an eye-...
15,/m/0814255,2010-03-05,Christianity Today,Fresh,NaN,NaN,While this flick may not have Harry Potter's c...
16,/m/0814255,2010-03-03,"Vue Weekly (Edmonton, Alberta)",Rotten,NaN,NaN,Another attempted launch of a teen-aimed franc...
17,/m/0814255,2010-02-24,rec.arts.movies.reviews,Fresh,NaN,7.0,What surprised me is that I had some affection...
18,/m/0814255,2010-02-19,"Commercial Appeal (Memphis, TN)",Fresh,NaN,NaN,"A fun, effects-filled, escapist adventure, wit..."
19,/m/0814255,2010-02-19,PopMatters,Rotten,NaN,NaN,It looks like the characters of color in Percy...
20,/m/0814255,2010-02-19,SFX Magazine,Fresh,NaN,NaN,"It's all jolly good fun, rattling along at a p..."
21,/m/0814255,2010-02-19,Tulsa World,Rotten,NaN,NaN,"A safe, bland, test-marketed product made for ..."
22,/m/0814255,2010-02-18,Christian Science Monitor,Fresh,NaN,NaN,"The whole thing is piffle, but it moves fast e..."
23,/m/0814255,2010-02-18,East Bay Express,Fresh,NaN,NaN,Grand prize goes to Uma Thurman as snake-heade...
24,/m/0814255,2010-02-18,I.E. Weekly,Rotten,Top Critic,NaN,The Greek gods had outsized powers and petty g...
25,/m/0814255,2010-02-18,Laramie Movie Scope,Fresh,NaN,NaN,An awful lot of acting talent goes to waste in...
26,/m/0814255,2010-02-17,MovieCrypt.com,Fresh,NaN,NaN,Remember the first time you saw Harry Potter o...
27,/m/0814255,2010-02-16,At the Movies,Fresh,Top Critic,NaN,I thought it was mischievous and witty and amu...
28,/m/0814255,2010-02-16,Birmingham Post,Fresh,NaN,NaN,The film is a rousing blend of special effects...
29,/m/0814255,2010-02-16,Daily Express (UK),Rotten,NaN,NaN,"Very American, very crass and very underwhelming."
...,...,...,...,...,...,...,...
930912,/m/zorba_the_greek,2003-11-20,Cleveland Press,Fresh,NaN,NaN,Zorba the Greek is a motion picture that is ri...
930913,/m/zorba_the_greek,2003-09-05,Las Vegas Review-Journal,Fresh,NaN,NaN,NaN
930914,/m/zulu,2017-07-10,Daily Telegraph (UK),Fresh,NaN,NaN,"It may not be truthful - but, my God, the resu..."
930915,/m/zulu,2017-07-10,Empire Magazine,Fresh,NaN,NaN,As a spectacular war film with a powerful mora...
930916,/m/zulu,2017-07-10,Guardian,Fresh,Top Critic,NaN,A brilliantly made dramatisation of Rorke's Dr...
930917,/m/zulu,2017-07-10,Los Angeles Times,Fresh,Top Critic,NaN,"This may not be exact history, but it certainl..."
930918,/m/zulu,2017-07-10,Radio Times,Fresh,NaN,NaN,The movie is a revelation.
930919,/m/zulu,2017-07-10,Sky Cinema,Fresh,NaN,NaN,"This is that rarity in films - an all-action, ..."
930920,/m/zulu,2015-05-30,Three Movie Buffs,Fresh,NaN,NaN,The old-fashioned war epic that made Michael C...
930921,/m/zulu,2009-05-01,Cinema em Cena,Fresh,NaN,NaN,"Responsvel por lanar a carreira de Caine, o fi..."
930922,/m/zulu,2009-01-02,Variety,Fresh,Top Critic,NaN,Joseph E. Levine makes an impressive debut in ...
930923,/m/zulu,2006-02-09,Time Out,Fresh,Top Critic,NaN,Zulu is a fairly tough-minded and interesting ...
930924,/m/zulu,2006-01-31,Filmcritic.com,Fresh,NaN,NaN,"Though, there's an awful lot of lounging aroun..."
930925,/m/zulu,2005-06-29,EmanuelLevy.Com,Fresh,NaN,NaN,NaN
930926,/m/zulu,2005-05-09,New York Times,Fresh,Top Critic,NaN,Students of such things in movies should appre...
930927,/m/zulu,2004-11-12,Boulder Weekly,Fresh,NaN,NaN,NaN
930928,/m/zulu,2004-10-08,Reeling Reviews,Fresh,NaN,NaN,NaN
930929,/m/zulu,2004-09-10,Las Vegas Review-Journal,Fresh,NaN,NaN,NaN
930930,/m/zulu,2003-07-23,Cinema Signals,Fresh,NaN,NaN,NaN
930931,/m/zulu,2002-02-19,rec.arts.movies.reviews,Rotten,NaN,NaN,Its failure to present any kind of historical ...
930932,/m/zulu,2000-01-01,Ozus' World Movie Reviews,Fresh,NaN,NaN,"Caine was just splendid, it is still one of hi..."
930933,/m/zulu,2000-01-01,TV Guide,Fresh,NaN,NaN,This amazing film is devastatingly accurate in...
930934,/m/zulu,1964-06-17,Eye for Film,Fresh,NaN,NaN,NaN
930935,/m/zulu_dawn,2011-02-28,Sarasota Herald-Tribune,Rotten,NaN,NaN,"A simple two-act story: Prelude to war, and th..."
930936,/m/zulu_dawn,2010-09-16,Ozus' World Movie Reviews,Fresh,NaN,NaN,A rousing visual spectacle that's a prequel of...
930937,/m/zulu_dawn,2007-03-07,"Mountain Xpress (Asheville, NC)",Fresh,NaN,NaN,"Seen today, it's not only a startling indictme..."
930938,/m/zulu_dawn,2005-11-02,Fantastica Daily,Rotten,NaN,NaN,NaN
930939,/m/zulu_dawn,2005-11-01,ColeSmithey.com,Fresh,NaN,NaN,NaN
930940,/m/zulu_dawn,2005-08-14,PopcornQ,Fresh,NaN,NaN,NaN
930941,/m/zulu_dawn,2005-06-25,EmanuelLevy.Com,Rotten,NaN,NaN,NaN

In [3]:
df = df.groupby(['rotten_tomatoes_link']).count()
df.reset_index(inplace=True)

In [4]:
df1 = df[['rotten_tomatoes_link','critic_top','review_content']]

In [5]:
df1.head()

                     rotten_tomatoes_link  critic_top  review_content
0                              /m/0814255          38             142
1                              /m/0878835          42             136
2                                   /m/10           2              13
3                 /m/1000013-12_angry_men           6              42
4  /m/1000079-20000_leagues_under_the_sea           5              21

In [6]:
RT_revenue = pd.read_csv('../Resources/tomato_revenue_crit.csv')
RT_movie_name = pd.read_csv('../Resources/rotten_tomatoes_movies.csv')

In [7]:
RT_movie_name = RT_movie_name[['rotten_tomatoes_link','movie_title']]

RT_revenue.set_index('Unnamed: 0', inplace=True)
RT_revenue.head()

,title,star_count,audience_rating,audience_count,audience_top_critics_count,audience_fresh_critics_count,audience_rotten_critics_count,revenue
Unnamed: 0,,,,,,,,
0,Percy Jackson & the Olympians: The Lightning T...,87,53.0,254287.0,38,71,73,226497209.0
1,10,46,53.0,14670.0,2,15,7,74865517.0
2,3:10 to Yuma,14,78.0,9224.0,6,26,1,70016220.0
3,Dark Water,8,66.0,21459.0,3,12,3,25473093.0
4,The Lost City,23,64.0,25940.0,37,21,62,4386236.0

In [8]:
merged = pd.merge(df1, RT_movie_name, how='left', right_on='rotten_tomatoes_link', left_on='rotten_tomatoes_link')

In [9]:
merged.head()

,rotten_tomatoes_link,critic_top,review_content,movie_title
0,/m/0814255,38,142,Percy Jackson & the Olympians: The Lightning T...
1,/m/0878835,42,136,Please Give
2,/m/10,2,13,10
3,/m/1000013-12_angry_men,6,42,12 Angry Men (Twelve Angry Men)
4,/m/1000079-20000_leagues_under_the_sea,5,21,"20,000 Leagues Under The Sea"

In [86]:
##merged.to_csv('../Resources/critic_review_count.csv')

In [12]:
revenue_reviews = RT_revenue.merge(merged, how='left', right_on='movie_title', left_on='title')

In [15]:
revenue_reviews.drop(columns=['movie_title'], inplace=True)

In [20]:
revenue_reviews.rename(columns={'critic_top': 'top_critic_review_count', 'review_content': 'review_count'}, inplace=True)
revenue_reviews = revenue_reviews[['title', 'rotten_tomatoes_link', 'star_count', 'audience_rating', 'audience_count', 'audience_top_critics_count', 'audience_fresh_critics_count', 'audience_rotten_critics_count', 'revenue', 'top_critic_review_count', 'review_count']]

In [21]:
revenue_reviews.head()

,title,rotten_tomatoes_link,star_count,audience_rating,audience_count,audience_top_critics_count,audience_fresh_critics_count,audience_rotten_critics_count,revenue,top_critic_review_count,review_count
0,Percy Jackson & the Olympians: The Lightning T...,/m/0814255,87,53.0,254287.0,38,71,73,226497209.0,38.0,142.0
1,10,/m/10,46,53.0,14670.0,2,15,7,74865517.0,2.0,13.0
2,3:10 to Yuma,/m/1000123-310_to_yuma,14,78.0,9224.0,6,26,1,70016220.0,6.0,24.0
3,3:10 to Yuma,/m/310_to_yuma,14,78.0,9224.0,6,26,1,70016220.0,54.0,218.0
4,Dark Water,/m/10002114-dark_water,8,66.0,21459.0,3,12,3,25473093.0,3.0,13.0

In [23]:
revenue_reviews.to_csv('../Resources/tomato_revenue_crit_reviews.csv')